#ifndef PAFYCTOOLSGUIDEFINITIONS_H
#define PAFYCTOOLSGUIDEFINITIONS_H

#define PAFYCTOOLSGUI_TITLE "PAFyC Tools Gui"
#define PAFYCTOOLSGUI_PARAMETERS_FILE_NAME "parameters_pafyctoolsgui.xml"
#define PAFYCTOOLSGUI_PARAMETERS_MODELDBMANAGERDEFINITIONS_PROJECT_TYPE_PAFYCTOOLS_PARAMETERS_FILE_NAME     "parameters_commands_pafyctools.xml"
#define PAFYCTOOLSGUI_AUTHOR_EMAIL "david.hernandez@uclm.es"
#define PAFYCTOOLSGUI_AUTHOR_EMAIL2 "dhernand@usal.es"

#define PAFYCTOOLSGUI_SETTINGS_FILE_NAME "pafyctoolsgui.ini"
#define PAFYCTOOLSGUI_SETTINGS_TAG_LAST_PATH "last_path"
#define PAFYCTOOLSGUI_SETTINGS_TAG_QGIS_PATH "qgis_path"
#define PAFYCTOOLSGUI_SETTINGS_TAG_OUTPUT_PATH "output_path"
#define PAFYCTOOLSGUI_DOCS_PATH "/docs/"
#define PAFYCTOOLSGUI_LASINFO_FILE  "lasinfo.exe"
#define PAFYCTOOLSGUI_PROGRAM_CONSOLE_FILE_NAME "pafyctoolsconsole.exe"

#define PAFYCTOOLSGUI_QGIS_BAT_ENVIRONMENT "/bin/o4w_env.bat"

#define PAFYCTOOLSGUI_DATE_STRING_FORMAT "yyyy-MM-dd"
#define PAFYCTOOLSGUI_DATE_TIME_STRING_FORMAT "yyyy-MM-dd HH:mm:ss"

#define PAFYCTOOLSGUI_NO_COMBO_SELECT " ... "

#define PAFYCTOOLSGUI_COMMAND_PLPPC "Plants location from photogrammetric point cloud"
#define PAFYCTOOLSGUI_COMMAND_PLPPC_PP "Plants location from photogrammetric point cloud: 1. Preprocessing"
#define PAFYCTOOLSGUI_COMMAND_PLPPC_PP_HELP_PDF_FILE "PlantsLocationFromPhotogrammetricPointCloud_1_Preprocessing.pdf"
#define PAFYCTOOLSGUI_COMMAND_PLPPC_PP_PROCESS_FILE "1_plppc_preprocessing.bat"
#define PAFYCTOOLSGUI_COMMAND_PLPPC_PP_PROCESS_FILE_LASTOOLS "1_plppc_preprocessing_lastools.bat"
#define PAFYCTOOLSGUI_COMMAND_PLPPC_PP_PROCESS_FILE_GDAL "1_plppc_preprocessing_gdal.bat"
#define PAFYCTOOLSGUI_COMMAND_PLPPC_PP_TAG_LASTOOLS_PATH "PLPPC_PP_LAStoolsPath"
#define PAFYCTOOLSGUI_COMMAND_PLPPC_PP_TAG_POINT_CLOUD_FILE "PLPPC_PP_PointCloudFile"
#define PAFYCTOOLSGUI_COMMAND_PLPPC_PP_TAG_ROI_SHAPEFILE "PLPPC_PP_ROIShapeFile"
#define PAFYCTOOLSGUI_COMMAND_PLPPC_PP_TAG_CRS_EPSG_CODE "PLPPC_PP_CRS_EPSG_CODE"
#define PAFYCTOOLSGUI_COMMAND_PLPPC_PL "Plants location from photogrammetric point cloud: 2. Plants location"
#define PAFYCTOOLSGUI_COMMAND_PLPPC_PL_HELP_PDF_FILE "PlantsLocationFromPhotogrammetricPointCloud_2_PlantsLocation.pdf"
#define PAFYCTOOLSGUI_COMMAND_PLPPC_PL_PROCESS_FILE "2_plppc_plants_location.bat"
#define PAFYCTOOLSGUI_COMMAND_PLPPC_PL_TAG_INPUT_PATH "PLPPC_PL_InputPath"
#define PAFYCTOOLSGUI_COMMAND_PLPPC_PL_TAG_CRS_EPSG_CODE "PLPPC_PL_CRS_EPSG_CODE"
#define PAFYCTOOLSGUI_COMMAND_PLPPC_PL_TAG_PROJECT_ID "PLPPC_PL_PROJECT_ID"
#define PAFYCTOOLSGUI_COMMAND_PLPPC_PL_TAG_ROI_SHAPEFILE "PLPPC_PL_ROIShapeFile"
#define PAFYCTOOLSGUI_COMMAND_PLPPC_PL_MODELMANAGEMET_FIRST_COMMAND "Create Crops Shapefile"


#endif // PAFYCTOOLSGUIDEFINITIONS_H
